#设置user-center的负载规则
user-center:
  ribbon:
    #按照集群优先分配
    NFLoadBalancerRuleClassName: com.alibaba.cententmyali.configure.NacosSameCusterWeightRule
    #NFLoadBalancerRuleClassName: com.alibaba.cententmyali.configure.NacosWeightRule #局部配置权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #随机访问策略


#ribbon设置 设置热加载 ，在tcc模式中这个是非常重要的 否者会抛出第一次异常的问题防止定义请求过完情况
ribbon:
  eager-load:
    enabled: true
    clients: user-center #其他服务用分号分隔 user-center,xxxx
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.10.5:8848 #nacos 配置 这里是ip：端口  或者是域名：端口 不能签名加上http：// ip : 端口
        cluster-name: BJ #nacose 配置集群名称 配置集群为BJ 北京机房
        metadata:
          version: v1
          target-version: v1
        #namespace: dc336d46-0e74-4eda-8192-f58bebb838a7
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel的dashboard
logging:
  level:
    #这里一定要debg 否者不会打印任何信息(不管是java 配置 还是 yml 配置 都需要这个)
    com.alibaba.cententmyali.feignclient.UserCenterFeign: debug
feign:
  client:
    config:
      # 你想配置的日志的微服务名称
      #user-center:
      # 改成default 就是全局的了
      default:
        loggerLevel: full
  httpclient:
    #开启feign 连接池 使用了apache HttpClient ，而不是使用默认的 urlConnect
    enabled: true
    #最大连接数 ,默认就是200个
    max-connections: 200
    #每个请求 就是路径，比如@getMapping("user/{1}") 这个连接的最大连接数，疑问 怎么能够使用max-connect 和 max-conenet-pre 这个连个参数达到
    #最好呢 配置大致的值，然后逐步优化
    max-connections-per-route: 50

#配置暴露的端点 '*' 就是暴露全部的端口  sentinel的暴露端口是 actuator/sentinel
management:
  endpoints:
    web:
      exposure:
        include: '*'

